# SQLite version 3.x
development:
  adapter: postgresql
  encoding: unicode
  database: chuvsu_dev
  pool: 5
  username: korobkov

test:
  adapter: postgresql
  encoding: unicode
  database: chuvsu_test
  pool: 5
  username: korobkov
